=== rocketpie/homelab/apps/restic-client/restic-client.schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "https://github.com/rocketpie/homelab/apps/restic-client/restic-client.schema.json",
  "title": "restic client configuration",
  "type": "object",
  "additionalProperties": false,
  "required": [
    "log",
    "resticBinary",
    "backupIgnoreFilename",
    "snapshotSchedule",
    "retentionSchedule",
    "repositories"
  ],
  "properties": {
    "log": {
      "type": "object",
      "additionalProperties": false,
      "required": [
        "path",
        "retainLogs"
      ],
      "properties": {
        "path": {
          "type": "string",
          "minLength": 1
        },
        "retainLogs": {
          "type": "string",
          "pattern": "^\\d{1,3}:\\d{2}:\\d{2}:\\d{2}$"
        }
      }
    },
    "resticBinary": {
      "type": "string",
      "minLength": 1
    },
    "backupIgnoreFilename": {
      "type": "string",
      "minLength": 1
    },
    "snapshotSchedule": {
      "type": "object",
      "additionalProperties": false,
      "required": [
        "enabled",
        "unit"
      ],
      "properties": {
        "enabled": {
          "type": "boolean"
        },
        "unit": {
          "type": "string",
          "minLength": 1
        }
      }
    },
    "retentionSchedule": {
      "type": "object",
      "additionalProperties": false,
      "required": [
        "enabled",
        "unit"
      ],
      "properties": {
        "enabled": {
          "type": "boolean"
        },
        "unit": {
          "type": "string",
          "minLength": 1
        }
      }
    },
    "repositories": {
      "type": "array",
      "minItems": 1,
      "items": {
        "type": "object",
        "additionalProperties": false,
        "required": [
          "name",
          "path",
          "resticRepository",
          "repositoryPassword",
          "snapshotAllowed",
          "restoreAllowed",
          "forgetAllowed",
          "resticBackupOptions",
          "forgetArgs"
        ],
        "properties": {
          "name": {
            "type": "string",
            "minLength": 1
          },
          "path": {
            "type": "string"
          },
          "resticRepository": {
            "type": "string",
            "minLength": 1
          },
          "repositoryPassword": {
            "type": "string",
            "minLength": 1
          },
          "snapshotAllowed": {
            "type": "boolean"
          },
          "restoreAllowed": {
            "type": "boolean"
          },
          "forgetAllowed": {
            "type": "boolean"
          },
          "backupPreCommand": {
            "type": "string"
          },
          "resticBackupOptions": {
            "type": "array",
            "items": {
              "type": "string"
            }
          },
          "forgetArgs": {
            "type": "array",
            "items": {
              "type": "string"
            }
          },
          "restUsername": {
            "type": "string"
          },
          "repositoryDisplay": {
            "type": "string"
          }
        }
      }
    }
  }
}

=== rocketpie/homelab/apps/restic-client/restic-client.example.json
{
  "log": {
    "path": "/var/log/restic-client",
    "retainLogs": "30:00:00:00"
  },
  "resticBinary": "/usr/local/bin/restic",
  "backupIgnoreFilename": ".backupignore",
  "snapshotSchedule": {
    "enabled": false,
    "unit": "restic-client-snapshot.timer"
  },
  "retentionSchedule": {
    "enabled": true,
    "unit": "restic-client-retention.timer"
  },
  "repositories": [
    {
      "name": "paperless",
      "snapshotAllowed": true,
      "restoreAllowed": true,
      "forgetAllowed": false,
      "resticRepository": "rest:http://paperless:SECRET@backup.lan:8000/paperless/paperless",
      "repositoryPassword": "RESTIC_REPOSITORY_PASSWORD",
      "path": "/media/paperless-data/export",
      "backupPreCommand": "/usr/local/bin/paperless-export-backup",
      "resticBackupOptions": [
        "--skip-if-unchanged"
      ],
      "forgetArgs": []
    }
  ]
}
